#!/usr/bin/env bash

##
# This file is part of `scr-be/src-run-bldr`
#
# (c) Rob Frawley 2nd <rmf@scr.be>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
##

set -e

if [[ ${BLDR_DEBUG} == "true" ]]
then
    set -x
fi

readonly _BLDR_PATH_NAME="`cd $(dirname ${BASH_SOURCE[0]}) && pwd`"
readonly _BLDR_BASE_NAME="`basename ${BASH_SOURCE[0]}`"
readonly _BLDR_FILE_PATH="${_BLDR_PATH_NAME}/${_BLDR_BASE_NAME}"
readonly _BLDR_ROOT_PATH="$(pwd)"

readonly _BLDR_SRC_NAME="BLDR: Project State Builder"
readonly _BLDR_SRC_AUTHOR="Rob Frawley 2nd <rmf AT src DOT run>"
readonly _BLDR_SRC_LICENSE="MIT License, https://rmf.mit-license.org>"
readonly _BLDR_SRC_VEMVER="0.9.0-development"

readonly _VALID_ACTION_TYPE=(up down)
readonly _VALID_ACTION_CONTEXT=(env app)
readonly _VALID_ACTION_CONTEXT_UP=(${_VALID_ACTION_CONTEXT[@]})
readonly _VALID_ACTION_CONTEXT_DN=(app env)

export _BLD_OUT_QUIET=0
export _BLD_OUT_VERY_QUIET=0
export _BLD_OUT_VERBOSE=0
export _BLD_OUT_VERY_VERBOSE=0
export _BLD_OUT_DEBUG=0

function outputError()
{
    printf "\n`tput setaf 1`%s: `tput sgr0`" "$1"
    printf "%s`tput sgr0`\n" "$2"
}

function outputWarning()
{
    if [[ ${_BLD_OUT_VERY_QUIET} -eq 0 ]]; then
        printf "\n`tput setaf 3`%s: `tput sgr0`" "$1"
        printf "%s`tput sgr0`\n" "$2"
    fi
}

function outputInfo()
{
    if [[ ${_BLD_OUT_QUIET} -eq 0 ]]; then
        outputWarning "$1" "$2"
    fi
}

function outputCommandInfo()
{
    printf "\n$(tput rev) %s $(tput sgr0)\nAuthor  : %s\nLicense : %s\nVersion : %s\n" \
        "$_BLDR_SRC_NAME" "$_BLDR_SRC_AUTHOR" "$_BLDR_SRC_LICENSE" "$_BLDR_SRC_VEMVER"
}

function outputCommandUsage()
{
    commands[2]='up-env'
    commands[3]='up-app'
    commands[5]='down-env'
    commands[6]='down-app'

    printf "\nUsage: "

    local iteration=1

    for C in ${commands[*]}; do
        if [[ ${iteration} -ne 1 ]]; then
            printf '       '
        else
            iteration=`echo $iteration + 1 | bc`
        fi

        printf "./`tput bold`%s [OPTIONS] -b %s`tput sgr0`\n" "$_BLDR_BASE_NAME" "$C"
    done

    printf "\nOptions:\n"
    printf "`tput bold`    -b `tput sgr0`   build mode: sets the runtime build mode for the session\n"
    printf "`tput bold`    -d `tput sgr0`   enable debug command trace output\n"
    printf "`tput bold`    -V `tput sgr0`   enable verbose output (use twice to increase verbosity)\n"
    printf "`tput bold`    -q `tput sgr0`   enable quiet output (use twice to silent)\n"
    printf "`tput bold`    -v `tput sgr0`   display script version string\n"
    printf "`tput bold`    -h `tput sgr0`   display this usage/help message\n\n"
}

function arrayContainsElement()
{
    local e

    for e in "${@:2}"; do
        [[ "$e" == "$1" ]] && return 0
    done

    return 1
}

while getopts ":hvdVqb:" opt; do
    case $opt in
        h)
            outputCommandUsage
            exit 255
        ;;

        v)
            outputCommandInfo
            exit 255
        ;;

        q)
            if [[ ${_BLD_OUT_VERBOSE} -eq 1 ]]; then
                outputError "Invalid option sequence" "Use of both the verbose \"-V\" and quiet \"-q\" options is prohibited as these options conflict."
                outputCommandUsage
                exit 255
            fi

            if [[ ${_BLD_OUT_QUIET} -eq 1 ]]; then
                export _BLD_OUT_VERY_QUIET=1
            fi
            export _BLD_OUT_QUIET=1
        ;;

        V)
            if [[ ${_BLD_OUT_QUIET} -eq 1 ]]; then
                outputError "Invalid option sequence" "Use of both the verbose \"-V\" and quiet \"-q\" options is prohibited as these options conflict."
                outputCommandInfo
                exit 255
            fi

            if [[ ${_BLD_OUT_VERY_VERBOSE} -eq 1 ]]; then
                export _BLD_OUT_DEBUG=1
            fi

            if [[ ${_BLD_OUT_VERBOSE} -eq 1 ]]; then
                export _BLD_OUT_VERY_VERBOSE=1
            fi

            export _BLD_OUT_VERBOSE=1
        ;;

        d)
            outputWarning "Debug mode enabled" "Issuing \"set -x\" to enable command tracing."
            set -x
            export _BUILDER_DEBUG=1
        ;;

        b)
            _BLDR_C="$OPTARG"
        ;;

        \?)
            outputError "Invalid option provided" "The passed option \"-$OPTARG\" is not valid."
            exit 255
        ;;
    esac
done

export _ACTION=$_BLDR_C
export _ACTION_TYPE=${_ACTION%-*}
export _ACTION_CONTEXT=(${_ACTION#*-})

if [[ ${_ACTION_TYPE} == 'dn' ]]; then
    _ACTION_TYPE='down'
fi

if [[ -z "${_BLDR_C+x}" ]]; then
    outputError "Invalid options" "The build mode must be provided via the \"-b\" option."
    outputCommandUsage
    exit 255
fi

if [[ ! "${_VALID_ACTION_TYPE[@]}" =~ "${_ACTION_TYPE}" ]]; then
    outputError "Invalid options" "The provided build type \"${_ACTION_TYPE}\" is invalid."
    outputCommandUsage
    exit 255
fi

if [[ ! "${_VALID_ACTION_CONTEXT[@]}" =~ "${_ACTION_CONTEXT}" ]]; then
    if [[ "${_ACTION_CONTEXT}" == "${_ACTION_TYPE}" ]]; then
        if [[ "${_ACTION_TYPE}" == "up" ]]; then
            _ACTION_CONTEXT=(${_VALID_ACTION_CONTEXT_UP[@]})
        else
            _ACTION_CONTEXT=(${_VALID_ACTION_CONTEXT_DN[@]})
        fi
    else
        outputError "Invalid options" "The provided build context \"${_ACTION_CONTEXT}\" is invalid."
        outputCommandUsage
        exit 255
    fi
fi

type writeLines &>> /dev/null || . ${_BLDR_PATH_NAME}/_common/common.bash

listing=(
    ":Runtime Enviornment" \
    "Enviornment:OS"       "${DISTRIB_ID} ${DISTRIB_RELEASE}"
    "Enviornment:Action"   "${_ACTION^^}" \
    "Enviornment:Location" "${env_location^^}" \
    "Enviornment:Travis"   "$(getYesOrNoForCompare ${env_location} ci)" \
    "Enviornment:Config"   "${_BLDR_ROOT_PATH}/${_PKG_ENV_VARIABLE}" \
    \
    ":PHP/Engine Information" \
    "Release:PHP"           "$(getMajorPHPVersion).x Series" \
    "Supported:PHP:Version" "$(getYesOrNoForCompare ${_VER_PHP_ON_UNSU:-x} "x") (PHP     v${_VER_PHP})" \
    "Supported:PHP:Engine"  "YES (Engine  ${_VER_PHPAPI_ENG}/${_VER_PHPAPI_MOD})" \
    "Supported:PHP:Xdebug"  "YES (Xdebug  v${_VER_PHP_XDEBUG})" \
    "Supported:PHP:Opcache" "YES (Opcache v${_VER_PHP_OPCACHE})" \
    "Installed:PHPEnv"      "$(echo ${env_with_phpenv} | tr '[:lower:]' '[:upper:]') ${env_ver_phpenv}" \
    "Installed:HHVM"        "$(echo ${env_with_hhvm} | tr '[:lower:]' '[:upper:]') ${env_ver_hhvm}" \
    \
    ":Package Configuration" \
    "Environment:Make"    "${scr_pkg_env_make:-NONE}" \
    "Environment:Prepare" "${scr_pkg_env_prep:-NONE}" \
    "Environment:Postrun" "${scr_pkg_env_post:-NONE}" \
    "PHP:Extensions"      "${scr_pkg_php_exts:-NONE}" \
    "PHP:Configuration"   "${scr_pkg_php_conf:-NONE}" \
    "Application:Prepare" "${scr_pkg_app_prep:-NONE}" \
    "Application:Postrun" "${scr_pkg_app_post:-NONE}" \
    "Application:Console" "${scr_pkg_app_path:-NONE}"
)

writeDefinitionListing "${listing[@]}"

if [ ! ${_VER_PHP_ON_5} ] && [ ! ${_VER_PHP_ON_7} ]; then
    writeError "Unsupported PHP version for auto-builds. Found ${_VER_PHP}."
fi

for context in ${_ACTION_CONTEXT[@]}; do
    export _ACTION="${_ACTION_TYPE}-${context}"
    export _ACTION_TYPE=${_ACTION%-*}
    export _ACTION_CONTEXT=(${_ACTION#*-})

    _ACTION_FILE_INCLUDE="${_BLDR_PATH_NAME}/$(basename ${_BLDR_BASE_NAME} .bash)_${_ACTION}.bash"

    if [[ ! -f ${_ACTION_FILE_INCLUDE} ]]; then
        writeWarning "$(printf 'Operation file "%s" does not exist!' ${_ACTION_FILE_INCLUDE})"
        exit 1
    fi

    writeSectionEnter "$(printf 'Running actions for "%s:%s" context' ${_ACTION_TYPE} ${_ACTION_CONTEXT})"
    writeDebugSourcedFile   "${_ACTION_FILE_INCLUDE}"
    . ${_ACTION_FILE_INCLUDE}
    writeSectionExit  "$(printf 'Running actions for "%s:%s" context' ${_ACTION_TYPE} ${_ACTION_CONTEXT})"
done

writeComplete "All operations for \"${_ACTION}\" routine completed without error."

exit 0

